Manage: Rework external Manage_remove() path
md-raid-utilities/mdadm pull request #31
Opened 2024-06-21 15:11 UTC by mtkaczyk

Kernel is returning `-ENODEV` if `HOT_REMOVE_DISK` ioctl is sent for array with no personality (external container). Manage_remove() for external metadata is projected to work only with container device. Rework the code to not execute the ioctl and to use sysfs way.

Motivation is to hide MD bug. Ioctl is waiting for timeout because MD_RECOVERY_NEEDED flag is set on container (which is probably incorrect).

Also it simplifies remove logic, we don't need to run full sysfs_scan to get the disk to remove. It is not introduced for native arrays. It is enough risk to try it with external metadata.

This pull request is not yet complete, it requires more testing and link handling improvements, for example (but is more overall mdadm issue than mine):

```
# ./mdadm --remove /dev/md127 /dev/disk/by-diskseq/11
mdadm: hot remove failed for /dev/disk/by-diskseq/11
```

2024-07-02 15:03 UTC, bkucman requested changes
Hi, 
Overall I agree with the change, I have a few minor questions or corrections.

Typo in commit desc ee89efad3181fb9adbf39f52d9fdd0d2e263349a
dediated -> dedicated

Unnecessary dots in commit titles

2024-07-05 09:11 UTC, mtkaczyk commented
@bkucman
thanks for review, For now moving again to draft, I opened new PR #46 - it is a preparation for this change and needs to come first.

2024-09-04 07:27 UTC, mtkaczyk commented
Part of this (support for devnode in mdadm -If) is moved to #87
After merging #87 I will get back to this PR.

2024-09-10 12:04 UTC, mtkaczyk commented on Incremental.c
> +				sysfs_set_str(&mdi, NULL, "array_state", "read-auto");
I don't think it is important, we have to try remove the device anyway.

2024-09-10 12:04 UTC, mtkaczyk commented on Incremental.c
> +	if (ent->metadata_version && strncmp(ent->metadata_version, "external:", 9) == 0) {
I think it part of it is done.

2024-09-10 12:06 UTC, mtkaczyk commented on Incremental.c
> +			if (strncmp(buf, "active", 6) == 0 || strncmp(buf, "clean", 5) == 0)
There are more places like that, so not in this patchset, sorry :(

2024-09-10 12:07 UTC, mtkaczyk commented on Incremental.c
> +							       verbose);
unfortunately not.

2024-11-27 07:57 UTC, mtkaczyk commented
I tested it functionally on my own with native and IMSM. No regression detected but it was minimal testing.
I will merge it after the release. I'm waiting for Kuai patches for bitmap right now and then I will make a release.

You can see testing result here:
https://github.com/md-raid-utilities/mdadm/actions/runs/11969166801/job/33369355291?pr=31
I see no new failure but I will look closer later.

2024-11-29 08:01 UTC, mtkaczyk commented
@ncroxon, comparing to Nightly execution on the latest main. I see `01r5fail` fixed probably by this PR.

`05r1-internalbitmap-v1c` is broken but this functionality and test will be removed soon.

2024-12-16 09:11 UTC, merged