mdadm managemon.c fix coverity issues
md-raid-utilities/mdadm pull request #52
Opened 2024-07-10 20:20 UTC by ncroxon

Fixing the following coding errors the coverity tools found:

* Event check_return: Calling "fcntl(fd, 4, fl)" without checking return value. This library function may fail and return an error code.

* Event check_after_deref: Null-checking "new" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.

2024-07-16 09:51 UTC, bkucman requested changes
Hi Nigel,
Please add a colon after "mdadm" in the commit title.
Overall LGTM.

Thanks.

2024-07-16 14:34 UTC, mtkaczyk requested changes
LGTM but please check status of first `fnctl` in read_sock.

2024-07-16 14:34 UTC, mtkaczyk commented on managemon.c
> +	if (fcntl(fd, F_SETFL, fl) < 0) {
`fnctl` is called two times but we are checking the result only on last attempt. I checked the man and it it not quarented that `F_GETFL` is always successful. We should check this status too.

2024-07-24 12:00 UTC, mtkaczyk commented
Hey @ncroxon,
Checkpatch job if failing. Please fix it here and in other pulls.
```
ERROR:ASSIGN_IN_IF: do not use assignment in if condition
#42: FILE: managemon.c:870:
+ if ((fl = fcntl(fd, F_GETFL, 0)) < 0) {
Error: ERROR:ASSIGN_IN_IF: do not use assignment in if condition
```

Thanks!

2024-07-24 13:05 UTC, ncroxon commented
Fixed and pushed.

no issues with checkpatch

$ /scripts/checkpatch.pl 0001-mdadm-managemon.c-fix-coverity-issues.patch
total: 0 errors, 0 warnings, 28 lines checked

0001-mdadm-managemon.c-fix-coverity-issues.patch has no obvious style 
problems and is ready for submission.

On 7/24/24 8:00 AM, Mariusz Tkaczyk wrote:
>
> Hey @ncroxon <https://github.com/ncroxon>,
> Checkpatch job if failing. Please fix it here and in other pulls.
>
> |ERROR:ASSIGN_IN_IF: do not use assignment in if condition #42: FILE: 
> managemon.c:870: + if ((fl = fcntl(fd, F_GETFL, 0)) < 0) { Error: 
> ERROR:ASSIGN_IN_IF: do not use assignment in if condition |
>
> Thanks!
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/md-raid-utilities/mdadm/pull/52#issuecomment-2247731996>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/A2EHI3KJR5H7SBO7ASJEQ73ZN6JPFAVCNFSM6AAAAABKVTYFZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBXG4ZTCOJZGY>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2024-07-24 18:28 UTC, bkucman approved these changes

2024-07-25 13:37 UTC, ktanska approved these changes

2024-07-30 14:05 UTC, merged