mdadm: msg.c fix coverity issues
md-raid-utilities/mdadm pull request #55
Opened 2024-07-16 13:06 UTC by ncroxon

Fixing the following coding errors the coverity tools found:

* Event check_return: Calling "fcntl(sfd, 4, fl)" without checking return value. This library function may fail and return an error code.

2024-07-16 14:36 UTC, mtkaczyk requested changes
LGTM but Please check first `fnctl` call.

2024-07-16 14:36 UTC, mtkaczyk commented on msg.c
>  	fl = fcntl(sfd, F_GETFL, 0);
Please check status of first `fnctl` call

2024-07-24 18:29 UTC, bkucman approved these changes

2024-07-30 14:06 UTC, mtkaczyk approved these changes

2024-07-30 14:06 UTC, merged