add checking of return status on fstat calls
md-raid-utilities/mdadm pull request #7
Opened 2024-05-15 17:39 UTC by ncroxon

There are a few places we don't check the return status when calling fstat for success. Clean up the calls by adding a check before continuing.

V2: clean up warnings/errors from checkpatch.pl

2024-05-16 05:58 UTC, mtkaczyk requested changes
Hey @ncroxon,
There is one small issue. Please fix it and we are ready to go :)

2024-05-16 05:58 UTC, mtkaczyk commented on Assemble.c
> +			}
You don't need braces in this case, there is one instruction inside if but it is not an issue, just FYI,

2024-05-16 05:58 UTC, mtkaczyk commented on Dump.c
> +	if (c->verbose >= 0) {
Oh, bracases here totally change the flow.

Previously, only `printf()` was executed verbose >=0. Now, the fsttat is executed. I think that it should be:
``` suggestion
	if (c->verbose >= 0)
		printf("%s saved as %s.\n", dev, fname);
	close(fl);
	ret = fstat(fd, &dstb);
	close(fd);

	if (ret) {
		unlink(fname);
		free(fname);
		return 1;
	}
```

2024-05-16 12:53 UTC, ncroxon commented
I pushed a new version (V3) to the branch.

2024-05-20 08:57 UTC, mtkaczyk commented
```
[PATCH V3] add checking of return status on fstat calls
There are a few places we don't check the return status when
calling fstat for success. Clean up the calls by adding a
check before continuing.

V3: fix Dump.c braces to execute verbose properly.
    clean up braces with only one instruction inside.
V2: clean up warnings/errors from checkpatch.pl

Signed-off-by: Nigel Croxon <ncroxon@redhat.com>
```

I will cherry-pick this commit so please remove [PATCH V3] from title and v2 and v3 changes from description.
We have to use comment to note changes from now.. thanks!

2024-05-21 07:11 UTC, merged