Mdmonitor: Fix startup with missing directory
md-raid-utilities/mdadm pull request #98
Opened 2024-09-25 11:42 UTC by asztukow

Commit a07dea8d3b78 ("Mdmonitor: Refactor check_one_sharer() for better error handling") introduced an issue, if directory /run/mdadm is missing, monitor fails to start. Move the directory creation earlier to ensure it is always created.

2024-09-25 12:28 UTC, mtkaczyk approved these changes

2024-09-25 14:07 UTC, ktanska approved these changes

2024-09-26 07:36 UTC, mku514k requested changes
I know this is a nitpick, but you missed first number from commit hash, that's why checkpatch complains, it should be 0a07dea8d3b78 (with 0 at the beginning).

2024-09-26 13:01 UTC, mku514k approved these changes

2024-09-27 09:09 UTC, merged